export type MockProvider = "openai" | "anthropic"

export type MockToolCall = {
	id: string
	name: string
	arguments: Record<string, unknown>
}

export type MockScenarioResponse =
	| {
			type: "text"
			text: string
	  }
	| {
			type: "tool_calls"
			toolCalls: MockToolCall[]
	  }
	| {
			type: "error"
			status: number
			message: string
	  }

export type MockScenarioContext = {
	provider: MockProvider
	body: Record<string, unknown>
}

export type MockScenario = {
	name: string
	resolve: (context: MockScenarioContext) => MockScenarioResponse
}

const hasToolResult = (body: Record<string, unknown>): boolean => {
	const messages = Array.isArray(body.messages) ? body.messages : []
	return messages.some((message) => {
		if (!message || typeof message !== "object") return false
		const role = "role" in message ? message.role : undefined
		if (role === "tool") return true
		const content = "content" in message ? message.content : undefined
		return Array.isArray(content)
			? content.some((block) => block && typeof block === "object" && "type" in block && block.type === "tool_result")
			: false
	})
}

const toolScenario = (name: string, toolName: string, args: Record<string, unknown>): MockScenario => ({
	name,
	resolve: ({ body }) =>
		hasToolResult(body)
			? { type: "text", text: `Mock ${toolName} result processed.` }
			: { type: "tool_calls", toolCalls: [{ id: `call_${toolName}`, name: toolName, arguments: args }] },
})

const scenarioList: MockScenario[] = [
	{
		name: "text-only",
		resolve: () => ({ type: "text", text: "Mock assistant response." }),
	},
	toolScenario("read-file", "read_file", { path: "src/app.ts" }),
	toolScenario("write-file", "write_to_file", {
		path: "src/mock-output.txt",
		content: "Generated by mock API server.",
	}),
	toolScenario("search-files", "search_files", {
		path: "src",
		regex: "MockAPIServer",
	}),
	toolScenario("execute-command", "execute_command", {
		command: "echo mock",
	}),
	{
		name: "multi-tool",
		resolve: ({ body }) =>
			hasToolResult(body)
				? { type: "text", text: "Mock multi-tool results processed." }
				: {
						type: "tool_calls",
						toolCalls: [
							{ id: "call_read_file", name: "read_file", arguments: { path: "src/app.ts" } },
							{ id: "call_search_files", name: "search_files", arguments: { path: "src", regex: "TODO" } },
						],
					},
	},
	{
		name: "error",
		resolve: () => ({ type: "error", status: 500, message: "Mock API error" }),
	},
]

const scenarios = new Map<string, MockScenario>(scenarioList.map((scenario) => [scenario.name, scenario]))

export function resolveScenario(name: string | undefined): MockScenario {
	return scenarios.get(name ?? "") ?? scenarios.get("text-only")!
}
