# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/webview-ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/types"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/evals"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/ipc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/telemetry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/prompt-engine"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/build"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/vscode-shim"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/mock-api-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/vscode-e2e"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/web-Njust-AI"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/web-evals"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
