export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/NJUST-AI/NJUST_AI",
	GITHUB_DISCUSSIONS: "https://github.com/NJUST-AI/NJUST_AI/discussions",
	DISCORD: "https://discord.gg/njust-ai",
	REDDIT: "https://reddit.com/r/NJUST_AI",
	X: "https://x.com/NjustAi",
	LINKEDIN: "https://www.linkedin.com/company/Njust-AI",
	TIKTOK: "https://www.tiktok.com/@njust-ai.code",
	BLUESKY: "https://bsky.app/profile/NjustAi.bsky.social",
	YOUTUBE: "https://www.youtube.com/@NJUST_AIYT",
	DOCUMENTATION: "https://docs.njust-ai.local",
	SLACK_DOCS: "https://docs.njust-ai.local/Njust-AI-cloud/slack-integration",
	CAREERS: "https://careers.njust-ai.local",
	ISSUES: "https://github.com/NJUST-AI/NJUST_AI/issues",
	FEATURE_REQUESTS: "https://github.com/NJUST-AI/NJUST_AI/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/NJUST-AI/NJUST_AI/discussions",
	CHANGELOG: "https://github.com/NJUST-AI/NJUST_AI/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/NJUST-AI/NJUST_AI/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.njust-ai.local/community",
	TUTORIALS: "https://docs.njust-ai.local/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=JunjieChen-YuyaoJiang.njust-ai",
	SECURITY: "https://trust.njust-ai.local",
	EVALS: "https://njust-ai.local/evals",
	BLOG_SUBSTACK: "https://blog.njust-ai.local",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@NJUST_AIYT/podcasts",
	FAQ: "https://njust-ai.local/#faq",
	TESTIMONIALS: "https://njust-ai.local/#testimonials",
	CLOUD_APP_LOGIN: "",
	CLOUD_APP_SIGNUP: "",
	CLOUD_APP_SIGNUP_HOME: "",
	CLOUD_APP_SIGNUP_PRO: "",
	CLOUD_APP_TEAM_TRIAL: "",
	SUPPORT: "mailto:support@njust-ai.local",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
