blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=JunjieChen-YuyaoJiang.njust-ai&ssr=false#review-details
      about: Enjoying NJUST_AI? Leave a review here!
