import { type ProviderName, type ModelInfo } from "@njust-ai/types"
import {
	anthropicModels,
	bedrockModels,
	deepSeekModels,
	moonshotModels,
	geminiModels,
	mistralModels,
	openAiNativeModels,
	openAiCodexModels,
	qwenCodeModels,
	qwenModels,
	doubaoModels,
	glmModels,
	vertexModels,
	xaiModels,
	sambaNovaModels,
	internationalZAiModels,
	fireworksModels,
	minimaxModels,
	basetenModels,
	mimoModels,
	mimoTokenPlanModels,
} from "@njust-ai/core/providers"

export const MODELS_BY_PROVIDER: Partial<Record<ProviderName, Record<string, ModelInfo>>> = {
	anthropic: anthropicModels,
	bedrock: bedrockModels,
	deepseek: deepSeekModels,
	moonshot: moonshotModels,
	gemini: geminiModels,
	mistral: mistralModels,
	"openai-native": openAiNativeModels,
	"openai-codex": openAiCodexModels,
	"qwen-code": qwenCodeModels,
	vertex: vertexModels,
	xai: xaiModels,
	sambanova: sambaNovaModels,
	zai: internationalZAiModels,
	fireworks: fireworksModels,
	minimax: minimaxModels,
	baseten: basetenModels,
	qwen: qwenModels,
	doubao: doubaoModels,
	glm: glmModels,
	mimo: mimoModels,
	"mimo-token-plan": mimoTokenPlanModels,
}

export const PROVIDERS = [
	{ value: "openrouter", label: "OpenRouter", proxy: false },
	{ value: "anthropic", label: "Anthropic", proxy: false },
	{ value: "gemini", label: "Google Gemini", proxy: false },
	{ value: "deepseek", label: "DeepSeek", proxy: false },
	{ value: "moonshot", label: "Moonshot", proxy: false },
	{ value: "openai-native", label: "OpenAI", proxy: false },
	{ value: "openai-codex", label: "OpenAI - ChatGPT Plus/Pro", proxy: false },
	{ value: "openai", label: "OpenAI Compatible", proxy: true },
	{ value: "qwen-code", label: "Qwen Code", proxy: false },
	{ value: "vertex", label: "GCP Vertex AI", proxy: false },
	{ value: "bedrock", label: "Amazon Bedrock", proxy: false },
	{ value: "vscode-lm", label: "VS Code LM API", proxy: false },
	{ value: "mistral", label: "Mistral", proxy: false },
	{ value: "lmstudio", label: "LM Studio", proxy: true },
	{ value: "ollama", label: "Ollama", proxy: true },
	{ value: "requesty", label: "Requesty", proxy: false },
	{ value: "xai", label: "xAI (Grok)", proxy: false },
	{ value: "litellm", label: "LiteLLM", proxy: true },
	{ value: "sambanova", label: "SambaNova", proxy: false },
	{ value: "zai", label: "Z.ai", proxy: false },
	{ value: "fireworks", label: "Fireworks AI", proxy: false },
	{ value: "vercel-ai-gateway", label: "Vercel AI Gateway", proxy: false },
	{ value: "minimax", label: "MiniMax", proxy: false },
	{ value: "baseten", label: "Baseten", proxy: false },
	{ value: "unbound", label: "Unbound", proxy: false },
	{ value: "qwen", label: "Qwen (通义千问)", proxy: false },
	{ value: "doubao", label: "Doubao (豆包)", proxy: false },
	{ value: "glm", label: "GLM (智谱清言)", proxy: false },
	{ value: "mimo", label: "Xiaomi MiMo", proxy: false },
	{ value: "mimo-token-plan", label: "Xiaomi MiMo Token Plan", proxy: false },
].sort((a, b) => a.label.localeCompare(b.label))
