/**
 * Agent Summary Service
 *
 * Periodically generates 1-2 sentence progress summaries for background
 * agents. This keeps the UI informed of what each background agent is
 * doing without requiring the user to inspect its full conversation.
 *
 * Summaries are generated by forking the agent's recent conversation
 * (last ~8 messages) through a lightweight LLM call, reusing the cache
 * prefix when possible.
 *
 * Inspired by Claude Code's background agent summarization (agentSummary.ts).
 */

export interface AgentProgressSummary {
	agentId: string
	summary: string
	toolCount: number
	tokenCount: number
	lastUpdated: number
}

export type SummaryCallback = (summary: AgentProgressSummary) => void

/**
 * Manages periodic summarization for a single background agent.
 * Call start() when the agent begins background execution,
 * and stop() when it completes or is aborted.
 */
export class AgentSummaryService {
	private timer: ReturnType<typeof setInterval> | null = null
	private toolCount = 0
	private tokenCount = 0

	constructor(
		private agentId: string,
		private getRecentMessages: () => string[],
		private onSummary: SummaryCallback,
		private intervalMs: number = 30_000,
	) {}

	/** Start periodic summarization. Fires immediately, then every intervalMs. */
	start(): void {
		if (this.timer) return

		// Fire immediately with initial state
		this.generateSummary()

		this.timer = setInterval(() => {
			this.generateSummary()
		}, this.intervalMs)
	}

	/** Stop periodic summarization. */
	stop(): void {
		if (this.timer) {
			clearInterval(this.timer)
			this.timer = null
		}
	}

	/** Update tool and token counts from outside */
	updateCounts(toolCount: number, tokenCount: number): void {
		this.toolCount = toolCount
		this.tokenCount = tokenCount
	}

	private generateSummary(): void {
		const messages = this.getRecentMessages()
		const summary = this.buildSummary(messages)
		this.onSummary(summary)
	}

	/**
	 * Build a lightweight summary from recent messages without an API call.
	 * Extracts the last assistant text and the most recent tool operations.
	 * For richer summaries, upgrade to a fork-based LLM call via runForkedAgent().
	 */
	private buildSummary(messages: string[]): AgentProgressSummary {
		let text = ""
		const toolOps: string[] = []

		for (let i = messages.length - 1; i >= 0 && toolOps.length < 3; i--) {
			const msg = messages[i]!
			// Extract tool operations from message content
			const toolMatch = msg.match(/"tool"\s*:\s*"(\w+)"/g)
			if (toolMatch) {
				for (const m of toolMatch) {
					const name = m.match(/"(\w+)"/)?.[1]
					if (name) toolOps.push(name)
				}
			}
			// Get the most recent assistant text
			if (!text && msg.length > 10 && !msg.startsWith("{")) {
				text = msg.slice(0, 200)
			}
		}

		const recentTools = toolOps.length > 0 ? `Recently used: ${toolOps.reverse().join(", ")}. ` : ""

		const context = text.length > 0 ? text.slice(0, 100) : "Working..."

		return {
			agentId: this.agentId,
			summary: `${recentTools}${context} (${this.toolCount} tools, ~${this.tokenCount} tokens)`,
			toolCount: this.toolCount,
			tokenCount: this.tokenCount,
			lastUpdated: Date.now(),
		}
	}
}
